# Generated by Django 3.2.6 on 2021-12-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AD_Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebarAD', models.TextField(blank=True, help_text='Left SideBar Ad', null=True)),
                ('newsSideAD', models.TextField(blank=True, help_text='News Sidebar Ad', null=True)),
                ('home_ad', models.TextField(blank=True, help_text='add between radio', null=True)),
                ('radio_ad', models.TextField(blank=True, help_text='add between radio', null=True)),
                ('access_name', models.CharField(default='admin', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_flag', models.CharField(blank=True, max_length=500, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RadioList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_name', models.CharField(blank=True, max_length=200, null=True)),
                ('radio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('play_link', models.CharField(blank=True, max_length=200, null=True)),
                ('rss_feed', models.CharField(blank=True, max_length=200, null=True)),
                ('popular', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_country', to='stations.countries')),
            ],
        ),
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radioCountryFeed', to='stations.countries')),
                ('source_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_radio', to='stations.radiolist')),
            ],
        ),
        migrations.CreateModel(
            name='RadioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_link', models.CharField(blank=True, max_length=200, null=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_history_session', to='stations.radiohistory')),
            ],
        ),
        migrations.AddField(
            model_name='radiohistory',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio', to='stations.radiolist'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_genre', to='stations.radiolist')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_category', to='stations.radiolist')),
            ],
        ),
    ]
